version: '3.1'

services:
  postgres-icsvalset:
    image: postgres:latest
    container_name: postgres-icsvalset
    environment:
      POSTGRES_DB: icsValsetMonitoring
      POSTGRES_USER: monitoring
      POSTGRES_PASSWORD: monitoring
    networks:
      - icsvalset_network
    volumes:
      - ./data/.icsValsetMonitoring_data:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: "500m"
        max-file: "5"
        labels: "postgres-log"

  grafana-icsvalset:
    image: grafana/grafana-oss:latest
    container_name: grafana-icsvalset
    entrypoint: /init-grafana.sh
    environment:
      - DB_HOST=${PG_HOST}:${PG_PORT}
      - DB_USER=${PG_USER}
      - DB_DBNAME=${PG_DBNAME}
      - DB_PWD=${PG_PWD}
    ports:
      - "3001:3000"
    depends_on:
      - postgres-icsvalset
    networks:
      - icsvalset_network
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./data/.grafana_data/data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/init-grafana.sh:/init-grafana.sh
    logging:
      driver: json-file
      options:
        max-size: "500m"
        max-file: "5"
        labels: "grafana-log"

  indexer-icsvalset:
    build: . 
    container_name: indexer-icsvalset
    depends_on:
      - postgres-icsvalset
    networks:
      - icsvalset_network
    environment:
      - DEPLOYMENT=${DEPLOYMENT}
      - PROVIDER_REST=${PROVIDER_REST}
      - PROVIDER_RPC=${PROVIDER_RPC}
      - SOVEREIGN_RPC=${SOVEREIGN_RPC}
      - CONSUMER_RPCS=${CONSUMER_RPCS}
      - NUM_WORKERS=${NUM_WORKERS}
      - PG_HOST=${PG_HOST}
      - PG_USER=${PG_USER}
      - PG_PORT=${PG_PORT}
      - PG_PWD=${PG_PWD}
      - PG_DBNAME=${PG_DBNAME}
    logging:
      driver: json-file
      options:
        max-size: "500m"
        max-file: "5"
        labels: "indexer-log"

networks:
  icsvalset_network:
    driver: bridge
