version: '3.1'

services:
  postgres-icsvalset:
    image: postgres:latest
    container_name: postgres-icsvalset
    environment:
      POSTGRES_DB: icsValsetMonitoring
      POSTGRES_USER: monitoring
      POSTGRES_PASSWORD: monitoring
    networks:
      - icsvalset_network
    volumes:
      - ./.icsValsetMonitoring_data:/var/lib/postgresql/data

  metabase-icsvalset:
    image: metabase/metabase:latest
    container_name: metabase-icsvalset
    ports:
      - "3000:3000"
    depends_on:
      - postgres-icsvalset
    networks:
      - icsvalset_network

  grafana-icsvalset:
    image: grafana/grafana-oss:latest
    container_name: grafana-icsvalset
    ports:
      - "3001:3000"
    depends_on:
      - postgres-icsvalset
    networks:
      - icsvalset_network
    volumes:
      - ./.grafana_data/provisioning:/etc/grafana/provisioning
      - ./.grafana_data/data:/var/lib/grafana
#      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=ccvalidators
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer

  indexer-icsvalset:
    build: . 
    container_name: indexer-icsvalset
    depends_on:
      - postgres-icsvalset
    networks:
      - icsvalset_network
    environment:
      - DEPLOYMENT=${DEPLOYMENT}
      - PROVIDER_REST=${PROVIDER_REST}
      - PROVIDER_RPC=${PROVIDER_RPC}
      - SOVEREIGN_RPC=${SOVEREIGN_RPC}
      - CONSUMER_RPCS=${CONSUMER_RPCS}
      - NUM_WORKERS=${NUM_WORKERS}

networks:
  icsvalset_network:
    driver: bridge