version: '3.1'

services:
  postgres-icsvalset:
    image: postgres:latest
    container_name: postgres-icsvalset
    environment:
      POSTGRES_DB: icsValsetMonitoring
      POSTGRES_USER: monitoring
      POSTGRES_PASSWORD: monitoring
    networks:
      - icsvalset_network

  metabase-icsvalset:
    image: metabase/metabase:latest
    container_name: metabase-icsvalset
    ports:
      - "3000:3000"
    depends_on:
      - postgres-icsvalset
    networks:
      - icsvalset_network

  grafana-icsvalset:
    image: grafana/grafana-oss:latest
    container_name: grafana-icsvalset
    ports:
      - "3001:3000"
    depends_on:
      - postgres-icsvalset
    networks:
      - icsvalset_network

  indexer-icsvalset:
    build: . 
    container_name: indexer-icsvalset
    depends_on:
      - postgres-icsvalset
    networks:
      - icsvalset_network
    environment:
      - DEPLOYMENT
      - PROVIDER_REST
      - PROVIDER_RPC
      - SOVEREIGN_RPC
      - CONSUMER_RPCS
      - NUM_WORKERS
      - GF_USERS_DEFAULT_THEME="dark"
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL="1s"

networks:
  icsvalset_network:
    driver: bridge
