{
 "title": "ics-consensus-consumer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "chainId",
    "label": "chainId",
    "query": "SELECT \"chainId\" FROM \"ChainInfo\";"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"height\"\nFROM \"ConsensusState\"\nWHERE \"chainId\" = '$chainId'\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"round\", \"step\"\nFROM \"ConsensusState\"\nWHERE \"chainId\" = '$chainId'\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Current Round",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM get_current_round('$chainId')"
    }
   ]
  },
  {
   "title": "Last Commit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT moniker, lastcommitvote, consensuspercentage FROM get_last_commit('$chainId')"
    }
   ]
  },
  {
   "title": "Pending Consumer-Signing-Key Updates",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH \"LatestConsensusState\" AS (\n    SELECT \"id\" AS \"latestConsensusStateId\"\n    FROM \"ConsensusState\"\n    WHERE \"chainId\" = '$chainId'\n    ORDER BY \"timestamp\" DESC\n    LIMIT 1\n),\n\"ActiveValidators\" AS (\n    SELECT \"id\" AS \"validatorId\"\n    FROM \"Validator\"\n    WHERE \"validatorsGroupId\" IN (\n        SELECT \"id\"\n        FROM \"ValidatorsGroup\"\n        WHERE \"consensusStateId\" = (SELECT \"latestConsensusStateId\" FROM \"LatestConsensusState\")\n    )\n),\n\"ChainType\" AS (\n    SELECT \"type\"\n    FROM \"ChainInfo\"\n    WHERE \"chainId\" = '$chainId'\n    LIMIT 1\n)\nSELECT \n    \"SV\".\"moniker\" AS \"stakingValidatorMoniker\",\n    CASE \n        WHEN \"SV\".\"consumer_signing_keys\" IS NULL THEN 'Consumer signing key not found'\n        ELSE (\"SV\".\"consumer_signing_keys\"::json)->>'$chainId'::text\n    END AS \"updatedConsumerSigningKey\"\nFROM \"StakingValidator\" \"SV\"\nLEFT JOIN \"Validator\" \"V\" ON \n    CASE \n        WHEN (SELECT \"type\" FROM \"ChainType\") = 'provider' THEN \"SV\".\"consensus_pubkey_key\" = (\"V\".\"pub_key\"::json)->>'value'\n        ELSE (\"SV\".\"consumer_signing_keys\"::json)->>'$chainId'::text = \"V\".\"consensusAddress\"\n    END\nWHERE \"V\".\"id\" IS NULL\nAND \"SV\".\"id\" IN (SELECT \"validatorId\" FROM \"ActiveValidators\");\n"
    }
   ]
  },
  {
   "title": "Onboarding Rate",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"consensusPercentage\" AS \"consensusPercentagePreVote\" FROM \"PreVote\" WHERE \"chainId\" = '$chainId';"
    },
    {
     "rawSql": "SELECT \"consensusPercentage\" AS \"precommitAgreePercentage\" FROM \"PreCommit\" WHERE \"chainId\" = '$chainId';"
    }
   ]
  },
  {
   "title": "Chain Info",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"chainId\", \"type\", \"clientIds\" FROM \"ChainInfo\" WHERE \"chainId\" = '$chainId';"
    }
   ]
  },
  {
   "title": "Prevote - Voting Power",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \"round\",\"total\",\"totalAgree\",\"totalNil\",\"totalZero\",\"consensusPercentage\" FROM \"PreVote\" WHERE \"chainId\" = '$chainId' ORDER BY \"id\" DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Precommit - Voting Power",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \"round\",\"total\",\"totalAgree\",\"totalNil\",\"totalZero\",\"consensusPercentage\" FROM \"PreCommit\" WHERE \"chainId\" = '$chainId' ORDER BY \"id\" DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT moniker, votingpower FROM get_current_validators_consumer('$chainId') ORDER BY votingpower DESC;"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Votes",
   "type": "table",
   "gridPos": { "h": 61, "w": 24, "x": 0, "y": 15 },
   "repeat": "chainType",
   "targets": [
    {
     "rawSql": "SELECT votingpower, prevote, precommit, moniker, operatoraddress, consumersigningkey FROM get_current_validators_consumer('$chainId') ORDER BY votingpower DESC;"
    }
   ]
  }
 ]
}