{
 "title": "ics-consensus-provider",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "chainId",
    "label": "chainId",
    "query": "SELECT \"chainId\" FROM \"ChainInfo\";"
   }
  ]
 },
 "panels": [
  {
   "title": "Chain Info",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"chainId\", \"type\" FROM \"ChainInfo\" WHERE \"chainId\" = '$chainId';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"height\"\nFROM \"ConsensusState\"\nWHERE \"chainId\" = '$chainId'\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Prevote",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \"round\",\"total\",\"totalAgree\",\"totalNil\",\"totalZero\",\"consensusPercentage\" FROM \"PreVote\" WHERE \"chainId\" = '$chainId' ORDER BY \"id\" DESC LIMIT 2;"
    }
   ]
  },
  {
   "title": "Onboarding Rate",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"consensusPercentage\" AS \"consensusPercentagePreVote\" FROM \"PreVote\" WHERE \"chainId\" = '$chainId';"
    },
    {
     "rawSql": "SELECT \"consensusPercentage\" AS \"consensusPercentagePreCommit\" FROM \"PreCommit\" WHERE \"chainId\" = '$chainId';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"round\", \"step\"\nFROM \"ConsensusState\"\nWHERE \"chainId\" = '$chainId'\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT moniker, votingpower FROM get_current_validators('$chainId') ORDER BY votingpower DESC;"
    }
   ]
  },
  {
   "title": "Current Round",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM get_current_round('$chainId')"
    }
   ]
  },
  {
   "title": "Precommit",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \"round\",\"total\",\"totalAgree\",\"totalNil\",\"totalZero\",\"consensusPercentage\" FROM \"PreCommit\" WHERE \"chainId\" = '$chainId' ORDER BY \"id\" DESC LIMIT 2;"
    }
   ]
  },
  {
   "title": "Last Commit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT moniker, lastcommitvote, consensuspercentage FROM get_last_commit('$chainId')"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "table",
   "gridPos": { "h": 61, "w": 24, "x": 0, "y": 12 },
   "repeat": "chainType",
   "targets": [
    {
     "rawSql": "SELECT votingpower, prevote, precommit, moniker, operatoraddress, consensuspubkey FROM get_current_validators('$chainId') ORDER BY votingpower DESC;"
    }
   ]
  }
 ]
}