name: CI

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker
      run: sudo apt update && sudo apt install -y docker docker-compose

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Create directories
      run: make create-dirs

    - name: Install NPM dependencies
      run: npm install
    
  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build services
      run: make docker-compose

    - name: Run services
      run: make docker-up

    - name: Validate config
      run: make config-validate

  cleanup:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Destroy containers
      run: make docker-destroy
